### ISSUE TITLE
Intergration with SteelSeriesMoments

### ISSUE THREAD

**Issue by Jakob-KB** [DataNext27/TouchPortal_SteelSeriesGG#1]
Hey, this isnt an issue of course. I was just curious to how ytou went about developing plugins for SteelSeries software. I'm concidering putting a plugin together to imporve SteelSeries Moments and it seems like you guys already have a good understanding of the systems.

**Comment by DataNext27** [comment]
Hi !
Basically, SteelSeries GG app runs a Rest API in the background to sort of communicate with itself or with its database. I used Wireshark to listen and capture the http traffic on my computer to get all the Http Put made by SS and use them in my code like SS would do.
I'm already looking to improve my plugin and add Moments controls but it seems like Moments don't use the Rest API so i have to find another way to control it.
