### ISSUE TITLE
Problème slider

### ISSUE THREAD

**Issue by NagoL2S** [DataNext27/TouchPortal_SteelSeriesGG#2]
Salut j’ai utilisé ton plugin il a l’air très bien j’ai essayé de mettre un slider r pour gérer l’audio sur le mode streamer et je n’ai pas réussi à le faire fonctionner correctement même avec npcap , je n’ai aps utilisé d’autres fonctions pourrais tu m’aider merci !

**Comment by DataNext27** [comment]
Ce sera fix dans le prochain patch
Désolé pour l'attente

**Comment by NagoL2S** [comment]
Salut
Pas de soucis en tout cas super projet je te remercie depuis le temps que je l’attend celui là, et auft je suis sur le Discord de TouchPortal il y a pas mal de personne qui cherche ce Plugin mais qu’ils ne savent pas qu’il existe, je te conseillerai d’y faire ta «promotion » et je crois que tu peux ouvrir ton canal ou tu mets les patch note etc

**Comment by DataNext27** [comment]
Super ! Merci de l'info !
