### ISSUE TITLE
Plugin Connectivity Issue with Sonar Integration

### ISSUE THREAD

**Issue by Asukiros** [DataNext27/TouchPortal_SteelSeriesGG#4]
Hi,

I've encountered a significant issue with the plugin's integration with Sonar, specifically pertaining to the bidirectional data exchange between Sonar and TouchPortal. Currently, the integration functions seamlessly when changes are made within Sonar, reflecting promptly in TouchPortal. However, the reverse flow of information, where updates made in TouchPortal are not syncing with Sonar, is failing to execute as intended.

Issue Details:
Upon thorough examination, it's apparent that the plugin's connection with Sonar is established effectively, allowing data to flow from Sonar to TouchPortal without hindrance. However, the failure arises when attempting to synchronize changes made within TouchPortal back to Sonar. Despite initiating updates via the TouchPortal interface on tablet devices, the corresponding changes fail to reflect in Sonar's environment.

I'm on Windows 11 and using GG Version 58.1.0.
And installed Npcap and .NET Runtime 7.0.

Thats a little of The log when trying to use a slider on Touch Portal but in this case nothing happens in Sonar.
> 20:12:53.340 - [LOG  ] [State System] Changed state tp_steelseries-gg_volume_Media from 64 to value 61
20:12:53.414 - [LOG  ] [Plugin Instance] Message send: {"data":[{"id":"streamermode","value":"Stream"},{"id":"mixerchoice","value":"Media"}],"pluginId":"steelseries-gg","connectorId":"tp_steelseries-gg_stream_set_volume","type":"connectorChange","value":55}
20:12:53.429 - [LOG  ] [Plugin Instance] 20:12:53 [HTTP Packet] 127.0.0.1:52559 -> 127.0.0.1:52198
20:12:53.429 - [LOG  ] [Plugin Instance] PUT /volumeSettings/streamer/streaming/media/volume/0.58 HTTP/1.1
20:12:53.429 - [LOG  ] [Plugin Instance] 
20:12:53.429 - [LOG  ] [State System] Changed state tp_steelseries-gg_volume_Media from 61 to value 58
20:12:53.515 - [LOG  ] [Plugin Instance] Message send: {"data":[{"id":"streamermode","value":"Stream"},{"id":"mixerchoice","value":"Media"}],"pluginId":"steelseries-gg","connectorId":"tp_steelseries-gg_stream_set_volume","type":"connectorChange","value":54}
20:12:53.535 - [LOG  ] [Plugin Instance] 20:12:53 [HTTP Packet] 127.0.0.1:52559 -> 127.0.0.1:52198
20:12:53.536 - [LOG  ] [Plugin Instance] PUT /volumeSettings/streamer/streaming/media/volume/0.55 HTTP/1.1
20:12:53.536 - [LOG  ] [Plugin Instance] 
20:12:53.536 - [LOG  ] [State System] Changed state tp_steelseries-gg_volume_Media from 58 to value 55
20:12:53.599 - [LOG  ] [Plugin Instance] 20:12:53 [HTTP Packet] 127.0.0.1:52559 -> 127.0.0.1:52198
20:12:53.599 - [LOG  ] [Plugin Instance] PUT /volumeSettings/streamer/streaming/media/volume/0.54 HTTP/1.1
20:12:53.599 - [LOG  ] [Plugin Instance] 
20:12:53.599 - [LOG  ] [State System] Changed state tp_steelseries-gg_volume_Media from 55 to value 54
20:12:54.070 - [LOG  ] [Plugin Instance] Message send: {"data":[{"id":"streamermode","value":"Stream"},{"id":"mixerchoice","value":"Media"}],"pluginId":"steelseries-gg","connectorId":"tp_steelseries-gg_stream_set_volume","type":"connectorChange","value":56}
20:12:54.166 - [LOG  ] [Plugin Instance] 20:12:54 [HTTP Packet] 127.0.0.1:52559 -> 127.0.0.1:52198
20:12:54.166 - [LOG  ] [Plugin Instance] PUT /volumeSettings/streamer/streaming/media/volume/0.56 HTTP/1.1
20:12:54.166 - [LOG  ] [Plugin Instance] 
20:12:54.167 - [LOG  ] [State System] Changed state tp_steelseries-gg_volume_Media from 54 to value 56

And here a little bit of the log when changing something in Sonar which works fine when updating in Touch portal.
>20:12:09.885 - [LOG  ] [Plugin Instance] 
20:12:09.885 - [LOG  ] [Plugin Instance] 20:12:09 [HTTP Packet] 127.0.0.1:52357 -> 127.0.0.1:52198
20:12:09.885 - [LOG  ] [Plugin Instance] PUT /volumeSettings/streamer/streaming/media/volume/0.96 HTTP/1.1
20:12:09.885 - [LOG  ] [Plugin Instance] 
20:12:09.885 - [LOG  ] [Plugin Instance] 20:12:09 [HTTP Packet] 127.0.0.1:52357 -> 127.0.0.1:52198
20:12:09.885 - [LOG  ] [Plugin Instance] PUT /volumeSettings/streamer/streaming/media/volume/0.99 HTTP/1.1
20:12:09.885 - [LOG  ] [Plugin Instance] 
20:12:09.885 - [LOG  ] [Plugin Instance] 20:12:09 [HTTP Packet] 127.0.0.1:52357 -> 127.0.0.1:52198
20:12:09.885 - [LOG  ] [Plugin Instance] PUT /volumeSettings/streamer/streaming/media/volume/1 HTTP/1.1
20:12:09.885 - [LOG  ] [Plugin Instance] 
20:12:09.885 - [LOG  ] [State System] Changed state tp_steelseries-gg_volume_Media from 97 to value 95
20:12:09.886 - [LOG  ] [State System] Changed state tp_steelseries-gg_volume_Media from 95 to value 99
20:12:09.886 - [LOG  ] [State System] Changed state tp_steelseries-gg_volume_Media from 99 to value 100
20:12:09.888 - [LOG  ] [State System] Changed state tp_steelseries-gg_volume_Media from 100 to value 96

Hope thats enough information :)

Thanks in advance!

**Comment by Asukiros** [comment]
Just a little Update,

Found out that otherwise if i am in classic mode its just the opposite? When i change something in TP it changes in sonar aswell but otherwise if i change in Sonar it doesnt update in TP.

Strange.

**Comment by DataNext27** [comment]
As I can tell by the logs, it seems you are not using the latest version au the plugin. This problem as already been fixed in newer updates, so maybe try downloading the newest release ?
You can download it here : [https://github.com/DataNext27/TouchPortal_SteelSeriesGG/releases/latest](https://github.com/DataNext27/TouchPortal_SteelSeriesGG/releases/latest)

You should also have received a notification on Touch Portal telling you that a new updates has been released

**Comment by Asukiros** [comment]
Hmm Strange,

I have installed the latest 1.1.2 version I tried it 4 Times with reinstalling SteelseriesGG aswell  .... and I even tried it again after deleting it and installed it again. It doesn't changes my Error unfortunaly.

and as i dont get that notification in Touch portal i suggest it is the right version that ist imported in Touch Portal :(

**Comment by DataNext27** [comment]
Yeah, sorry i've missunderstood what you were trying to say...
Acutally when you are in Streamer Mode, using a Touch Portal slider will not update SteelSeriesGG's sliders and i can't do anything about it since it's a GG bug. But normally the volume should change. Trying playing some music and trying moving the media slider on touch portal to test out

**Comment by Asukiros** [comment]
Ah I see, 

Ok thanks u're right. It really changes ... didnt noticed it when i tested it first ... !

Thanks for that hope it will be working in the future :D

have a Good Day/Evening and keep up the good work.

**Comment by DataNext27** [comment]
You're welcome !
Have a good day too !
Cheers !
