### ISSUE TITLE
Clarify state names

### ISSUE THREAD

**Issue by Razortide** [DataNext27/TouchPortal_SteelSeriesGG#5]
Hey Data,

as discussed in Discord, I have found if you are checking for the Plugin state, the output is not very clear: 

![image](https://github.com/DataNext27/TouchPortal_SteelSeriesGG/assets/35796457/b276468a-d1b7-4346-8aae-df3817a9c2fd)

By counting the different categories you can already select the right one, but to make it better you could add the category somewhere in the name as well, so it is easier to identify the right state to check.

**Comment by Razortide** [comment]
Hm, counting doesn't seem to work unfortunately...

**Comment by DataNext27** [comment]
Fixed in the new update !
