### ISSUE TITLE
.net framework

### ISSUE THREAD

**Issue by dmvdbrugge** [DataNext27/TouchPortal_SteelSeriesGG#9]
When installing this plugin, I learned two things about its .net requirement (being, 7.0):

1. It's a no longer supported version;
2. This plugin does *not* work with the latest version of .net (9.0).

I hope you will consider making it forwards compatible, or even better: backwards compatible assuming current latest as default.

If not, then please at least update the readme to specify that the required version is MS-unsupported, and that MS-supported versions are unsupported by this plugin.

**Comment by DataNext27** [comment]
I'm working on a full rework/rewrite of the plugin, it takes some times sorry
But i take note don't worry

**Comment by DataNext27** [comment]
It should be good now!
